name: Hola Mundo

on:
  push:
    branches:
      - master  # Cambia 'main' por el nombre de tu rama principal si es diferente

jobs:
  ejecutar_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Correr script
        run: python hola.py
